export const environment = {
  production: true,
  apiUrl: "https://localhost:7098",
  Login: "/auth/login",
  Register: "/auth/register",
  Logout: "/auth/logout",
  RefreshToken: "/auth/refresh",
  GetOwnCustomerData: "/customers/GetOwnCustomerData",
  CreateCustomer: "/customers/CreateCustomer",
  UpdateIncomeMonthly: "/customers/UpdateIncomeMonthly",
  SendLoanRequest: "/loan-applications/SendLoanRequest",
  GetLoanRequested: `/loan-applications/GetLoanRequested`,
  DecideLoan: "/loan-applications/:id/decision",
  GetLoans: "/loan-applications/GetLoans",
};
